language: ruby
rvm: ruby-2.1.9
cache: bundler
script:
  - echo "============ this is a placeholder for real tests that pass"
bundler_args: "--without system_tests"
before_install:
  - gem update bundler
  - "echo \"-.-.-.-.-. TRAVIS_TAG='${TRAVIS_TAG}'  TRAVIS_BRANCH='${TRAVIS_BRANCH}'\""
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.8.0"
# --------------------------------------
#
# ## Releng process
#
# ### Sanity checks
#
#   - [X] the tag and the module version must match
#
# ### Deploy tasks
#
#   - [ ] Push to Puppet Forge
#   - [ ] Create a Github release
#
# --------------------------------------
before_deploy:
  - "export PUPMOD_METADATA_VERSION=`ruby -r json -e \"puts JSON.parse(File.read('metadata.json')).fetch('version')\"`"
  - env
  - '[[ $TRAVIS_TAG =~ ^${PUPMOD_METADATA_VERSION}$ ]]'
  - 'bundle exec rake metadata_lint'
deploy:
  - provider: puppetforge
    user: poxvupuli
    password:
      secure: f1CgLroKi0xTADz2wJt6uQXBs+SqANKXoTiyjFGH/xlAuG7TA3VAXvaRQODgQ7xB+87JbBJSBkq4A/yCV04e5xVOss5GQJRGya0X2YghJpnrS6WJ4SWQ/1zh/fxTFmYqNNvTZT38aTOTEYozt2KazNIbAIC6/4E5/tWk4B/XfgDiiurd4HiT9qnnghmxfLb1iGqvVdp+sbP9QWalWEvda01HyXDyVor7uHMYMC4O5nWxEHlwZ8UNXqGwH5tBLuShMNiOGatD+CNDI4Tjqw3hAb0/wQO1Np6oHp9e0uADnNyRTp6Rz1H53vyNamim7DTa13EL+IlIbfcyszMALRtAMON3zFnknwhLqpmCbK85GBfc/BI8R27vsicAGWCumeaOEXZ8X5pRYVbfwylzkfsiDDYg5jX5DZvWO34Yk5+/Az4OFP584OO/4G1ZNk0hTuCWgh7vL/WiHcxmed/7JK/E+gKpsyD/ky4mtK8g0F4u69C+d+06+Q+IkoUV5RvzYBigyagKBw1aXs0kStcYOCXxodKY4o6Pq8LdYFzraWXF4j50/qEbgFUftGnduhi2ljt/htAxcWHbBCeY21QsfIgCiXQt3SjcyU9opIrJkF4b0GTyNQ9oEt22q8PpNWlltdeLEphxvLo4hK1AvaBOadLnjAku7+piOfHFfzrl5guF+YY=
    on:
      tags: true
      rvm: 2.1.9
      condition: '$FORGE_PUBLISH = true'
  - provider: releases
    api_key:
      secure: "PFvDMkQqEqWsXbef6/QUo0ejwdi+jlw1OQSLsNlbkMj0p3nZwXT47bX0GCxkHsNeH5dFf+t7AFYsh3woJjd+rzyGIqGl7CM4086nlSZsjT4ov3USOtHMCbcfqqLqiu7YBIoVWaM8vZb2tUBoRnzp2lcCzwY3H2CyWwRzr3CDygkxuVcBYn5nLsOzV/h0tpzmgHiC3KGo/TlOyOQXjukHBvTeZX7xMpc0RYTX2nBfNHDEbaMFfNpQwvcn10u+NccMQdArC82YMeCRmdGYTcNTVFWfprNKgt5KAWWnkkD2qh/QncCcouUwIoD34jZBoYAStB5h/KdQVeY5JRVUvzIWNb8ZScV3H5XHxwt3yJxGXkbsJFnMjKTj0zl8Na6H0UFIobXjKa4BqYQp8z7ulfeWEvpNg2U7dMgiOZC0b3Mxc5NG6rnwww+8HM0zfx0Uay1IcYxKFdE0ngcHgc+vgopjNPXEc0BcfgJRcpXfCorwJrlhR8vE9000bIXkx7ztsA6AeW9s+pB+RGpCB9ApEoJGVuw3lvXFUi05YbEow9xG1Cnm6qkm51iCSjh7b68hNFLz1d5ooHgoqVvLETBeajWXd89Y0E3BBgg1mNKe2fDXHRAYk1AcUK0tq1Aia7RNZNoUydaN3xHaIDyvpmHKtcTuUVCebF9esbubUxW6VOT3BcQ="
    skip_cleanup: true
    on:
      tags: true
      condition: '$FORGE_PUBLISH = true'

notifications:
  email: false
